CREATE TABLE Medium_Stats
    (id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    -- Alternatively can you use 'ID Number generated always as identity'? --
     json_Payload CLOB
    ) 
    LOGGING 
;
 
ALTER TABLE Medium_Stats
    ADD  CONSTRAINT checkforjson CHECK (json_Payload IS JSON);

BEGIN
    Insert into Medium_Stats
    (id, Json_Payload)
    Values
    (:id, :body_text)
    :status_code: 201;
END;

